### ISSUE TITLE
[Errno 2] No such file or directory: 'data/unc/corpus.pth'

### ISSUE THREAD

**Issue by wangxiao5791509** [BCV-Uniandes/DMS#18]
**Hi, I try to run this code, but get the following error. where should I download this missed 'data/unc/corpus.pth' file ?** 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/wangxiao/b8efbc67-7ea5-476d-9631-70da75f84e2d/reference_code/DMS/dmn_pytorch/train.py", line 177, in <module>
    max_query_len=args.time)
  File "/media/wangxiao/b8efbc67-7ea5-476d-9631-70da75f84e2d/reference_code/DMS/dmn_pytorch/referit_loader.py", line 89, in __init__
    self.corpus = torch.load(corpus_path)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/unc/corpus.pth'

**Comment by wangxiao5791509** [comment]
@andfoy Thanks for your kind explanation. It worked, this is a cool work.

**Comment by baihuple** [comment]
Hello,sir. I got the same problem and cannot solve it.
Traceback (most recent call last):
  File "d:\baihuple_File\BigFour\graduate_design\RIS_Paper\Paper1-toR\SHNET-main\main.py", line 368, in <module>
    main(args)
  File "d:\baihuple_File\BigFour\graduate_design\RIS_Paper\Paper1-toR\SHNET-main\main.py", line 245, in main
    train_dataset = ReferDataset(
                    ^^^^^^^^^^^^^
  File "d:\baihuple_File\BigFour\graduate_design\RIS_Paper\Paper1-toR\SHNET-main\dataloader\referit_loader.py", line 136, in __init__
    self.corpus = torch.load(corpus_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\torch\serialization.py", line 987, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\torch\serialization.py", line 436, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\torch\serialization.py", line 417, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\baihuple_File\\BigFour\\graduate_design\\RIS_Paper\\Paper1-toR\\refer-master\\data\\data\\unc\\corpus.pth'
Hope to get your help and I'll be very grafful.
