### ISSUE TITLE
AttributeError: 'Program' object has no attribute '_program'

### ISSUE THREAD

**Issue by WangLanxiao** [BCV-Uniandes/DMS#25]
when I run the train.py in pycharm
/home/lanxiao/anaconda3/envs/torch/bin/python /home/lanxiao/DMS-master/dmn_pytorch/train.py
Argument list to program
--data ../referit_data
--split_root data
--save_folder weights/
--snapshot weights/qseg_weights.pth
--num_workers 2
--dataset unc
--split train
--val None
--eval_first False
--workers 4
--no_cuda False
--log_interval 200
--backup_iters 10000
--batch_size 1
--epochs 40
--lr 1e-05
--patience 2
--seed 1111
--iou_loss False
--start_epoch 1
--optim_snapshot weights/qsegnet_optim.pth
--accum_iters 100
--pin_memory False
--size 512
--time -1
--emb_size 1000
--hid_size 1000
--vis_size 2688
--num_filters 10
--mixed_size 1000
--hid_mixed_size 1005
--lang_layers 3
--mixed_layers 3
--backend dpn92
--mix_we False
--lstm False
--high_res False
--upsamp_mode bilinear
--upsamp_size 3
--upsamp_amplification 32
--dmn_freeze False
--visdom None
--env DMN-train
Train begins...
/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "/home/lanxiao/DMS-master/dmn_pytorch/train.py", line 445, in <module>
    train_loss = train(epoch)
  File "/home/lanxiao/DMS-master/dmn_pytorch/train.py", line 275, in train
    out_masks = net(imgs, words)
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lanxiao/DMS-master/dmn_pytorch/models/dmn.py", line 450, in forward
    out, features = self.langvis(vis, lang)
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lanxiao/DMS-master/dmn_pytorch/models/dmn.py", line 156, in forward
    lang, _ = self.lang_model(lang)
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/sru/cuda_functional.py", line 635, in forward
    h, c = rnn(prevx, c0[i])
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/sru/cuda_functional.py", line 575, in forward
    SRU_Compute = SRU_Compute_GPU(self.activation_type, n_out, self.bidirectional)
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/sru/cuda_functional.py", line 333, in __init__
    self.compile()
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/sru/cuda_functional.py", line 348, in compile
    prog = Program(SRU_CODE.encode(), 'sru_prog.cu'.encode())
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/pynvrtc/compiler.py", line 52, in __init__
    include_names)
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/pynvrtc/interface.py", line 200, in nvrtcCreateProgram
    c_char_p(encode_str(src)), c_char_p(encode_str(name)),
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/pynvrtc/interface.py", line 54, in encode_str
    return s.encode("utf-8")
AttributeError: 'bytes' object has no attribute 'encode'
Exception ignored in: <bound method Program.__del__ of <pynvrtc.compiler.Program object at 0x7f99511ed5f8>>
Traceback (most recent call last):
  File "/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/pynvrtc/compiler.py", line 56, in __del__
    self._interface.nvrtcDestroyProgram(self._program)
AttributeError: 'Program' object has no attribute '_program'
-------------------------------------------------------------------------------
what is the main question?

**Comment by andfoy** [comment]
Hi, this is a known issue on the SRU. Sadly, you must edit this file (``/home/lanxiao/anaconda3/envs/torch/lib/python3.6/site-packages/sru/cuda_functional.py``) yourself. You need to remove the calls to ``encode()`` on line 348

**Comment by andfoy** [comment]
@WangLanxiao I assume that this issue was fixed. Feel free to reopen it if you have more questions related to this issue.
