### ISSUE TITLE
No such file or directory: 'data\\unc\\corpus.pth'?   what is this corpus.pth? Need download?

### ISSUE THREAD

**Issue by xiaoyuan1996** [BCV-Uniandes/DMS#33]
Traceback (most recent call last):
  File "E:/DMS-master/dmn_pytorch/train.py", line 179, in <module>
    max_query_len=args.time)
  File "E:\DMS-master\dmn_pytorch\referit_loader.py", line 91, in __init__
    self.corpus = torch.load(corpus_path)
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data\\unc\\corpus.pth'

**Comment by xiaoyuan1996** [comment]
Also, 
Traceback (most recent call last):
  File "E:/DMS-master/dmn_pytorch/train.py", line 178, in <module>
    max_query_len=args.time)
  File "E:\DMS-master\dmn_pytorch\referit_loader.py", line 99, in __init__
    self.images += torch.load(imgset_path)
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Anaconda\lib\site-packages\torch\serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data\\unc\\unc_train.pth'

is directory unc I missed?

**Comment by xiaoyuan1996** [comment]
ok Sorry,   I have sovled it by closed issue
